BEGIN;

-- 1. Game Table
CREATE TABLE IF NOT EXISTS "Game" (
    "Id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Game" PRIMARY KEY,
    "ShortName" TEXT NOT NULL,
    "GameName" TEXT NOT NULL,
    "VersionNum" INTEGER NOT NULL DEFAULT 0,
    "OwnerId" INTEGER NULL  -- Links to User.Id (if a user uploaded it)
);

-- 2. Trophy Table
CREATE TABLE IF NOT EXISTS "Trophy" (
    "Id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Trophy" PRIMARY KEY,
    "GameId" INTEGER NOT NULL,
    "TrophyName" TEXT NOT NULL,
    "TrophyDescription" TEXT NOT NULL,
    "MaxProgress" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "FK_Trophy_Game_GameId" FOREIGN KEY ("GameId") REFERENCES "Game" ("Id") ON DELETE CASCADE
);

-- 3. Image Table (Stores binary data for icons)
CREATE TABLE IF NOT EXISTS "Image" (
    "Id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Image" PRIMARY KEY,
    "GameId" INTEGER NOT NULL,
    "TrophyId" INTEGER NOT NULL,
    "Achieved" BOOLEAN NOT NULL, -- True=Trophy Icon, False=Locked Icon
    "data" BYTEA NULL
);

-- 4. UserStat Table (Links Users to Trophies)
CREATE TABLE IF NOT EXISTS "UserStat" (
    "Id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_UserStat" PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "GameId" INTEGER NOT NULL,
    "TrophyId" INTEGER NOT NULL,
    "Achieved" BOOLEAN NOT NULL DEFAULT FALSE,
    "Progress" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "FK_UserStat_Game_GameId" FOREIGN KEY ("GameId") REFERENCES "Game" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserStat_Trophy_TrophyId" FOREIGN KEY ("TrophyId") REFERENCES "Trophy" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserStat_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Game_ShortName" ON "Game" ("ShortName");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserStat_User_Game_Trophy" ON "UserStat" ("UserId", "GameId", "TrophyId");
CREATE INDEX IF NOT EXISTS "IX_Game_OwnerId" ON "Game" ("OwnerId");
CREATE INDEX IF NOT EXISTS "IX_Trophy_GameId" ON "Trophy" ("GameId");
CREATE INDEX IF NOT EXISTS "IX_UserStat_GameId" ON "UserStat" ("GameId");
CREATE INDEX IF NOT EXISTS "IX_UserStat_TrophyId" ON "UserStat" ("TrophyId");


COMMIT;