BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "Game" (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ShortName" TEXT NOT NULL UNIQUE,
    "GameName" TEXT NOT NULL,
    "VersionNum" INTEGER NOT NULL DEFAULT 0,
    "OwnerId" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "Trophy" (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "GameId" INTEGER NOT NULL,
    "TrophyName" TEXT NOT NULL,
    "TrophyDescription" TEXT NOT NULL,
    "MaxProgress" INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY("GameId") REFERENCES "Game"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Image" (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "GameId" INTEGER NOT NULL,
    "TrophyId" INTEGER NOT NULL,
    "Achieved" INTEGER NOT NULL, -- 0/1
    "data" BLOB NULL
);

CREATE TABLE IF NOT EXISTS "UserStat" (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "UserId" INTEGER NOT NULL,
    "GameId" INTEGER NOT NULL,
    "TrophyId" INTEGER NOT NULL,
    "Achieved" BOOLEAN NOT NULL DEFAULT 0, -- SQLite uses 0/1 for Boolean
    "Progress" INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY ("GameId") REFERENCES "Game" ("Id") ON DELETE CASCADE,
    FOREIGN KEY ("TrophyId") REFERENCES "Trophy" ("Id") ON DELETE CASCADE,
    FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Trophy_GameId" ON "Trophy" ("GameId");
CREATE INDEX IF NOT EXISTS "IX_UserStat_GameId" ON "UserStat" ("GameId");
CREATE INDEX IF NOT EXISTS "IX_UserStat_TrophyId" ON "UserStat" ("TrophyId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserStat_User_Game_Trophy" ON "UserStat" ("UserId", "GameId", "TrophyId");

COMMIT;