BEGIN;

CREATE TABLE IF NOT EXISTS "User" (
    "Id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_User" PRIMARY KEY,
    "UserName" TEXT NOT NULL,
    "Password" TEXT NOT NULL,  -- Note: In your code this maps to PasswordHash
    "Email" TEXT NOT NULL,
    
    -- NEW FIELDS FOR AUTH FLOW
    "PendingEmail" TEXT NULL,          -- For email change verification
    "VerificationToken" TEXT NULL,     -- For email verify/password reset
    "TokenExpiration" TIMESTAMP NULL,  -- When the token dies
    
    "Admin" BOOLEAN NOT NULL DEFAULT FALSE,
    "Visible" BOOLEAN NOT NULL DEFAULT TRUE,
    "Approved" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_User_UserName" ON "User" ("UserName");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_User_Email_Lower" ON "User" (LOWER("Email"));

COMMIT;